# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:Cnhz8pXCAPUZEuhA9f19wJlAeQBStMVfCs+K/he+HhP6nuUQUjFRQWmC1jypxzyZj2RnmepWBCGyLQ==,iv:cpOHIdpGSypzoMu0+klzHMa1HXtEG3rslI2GhVYbwbU=,tag:O+g3Q4Ys4vzoIkELO5opWw==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:oy/Mcdb/,iv:0PxdMVxIbj2GGeZnRUESju+mP+9C8SrsbXe0RFC+Csk=,tag:OGTPUDoCHJP0AOuIeOZ3bw==,type:int]
        mode: FIXED_PIN
    device:
        buttonGpio: 38
        buzzerGpio: 24
        disableTripleClick: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        autoScreenCarouselSecs: 15
        displaymode: INVERTED
        screenOnSecs: 30
        units: IMPERIAL
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:kWlSjTY9UemlKwyEPAsAMQlO/5NpFde8ZY59CUouSIiiOUD8AKMXC4BquR76tJFSmR9H,iv:Caf3T8/DE5knEUz87u6/RcqwIz8UPW2U/DT7KRHwOac=,tag:vzjDvQVaNKrk979I/Imu+g==,type:str]
        publicKey: base64:jb9jh5EqfDjBVOCmIF4uy+vdkYpz8bPTls2x15im5y4=
module_config:
    cannedMessage:
        allowInputSource: rotEnc1
        inputbrokerEventCcw: RIGHT
        inputbrokerEventCw: LEFT
        inputbrokerPinA: 6
        inputbrokerPinB: 8
        rotary1Enabled: true
owner: Meshtastic 18e7
owner_short: "18e7"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY2ZHR0tnd0tEdVZodzNQ
            UXpCWlpNQVNOS2YzMHRiNTBFMVp6OUF4WWt3CkNndUk2VUpySWNTOUtKYmtwZ3lx
            Snh4R2ozT2FZVi9pN1liUWlsYXp0T0EKLS0tIFFPQk5wRnVYbXhYdVBCWmpTYlZT
            elM4YkVMYk15UXd5TUwxVTdZRENlTjgK1dav5pSEFGYa/dWgSeIeMLF+YUdcEXBQ
            BkkHMZ6AzqozOUQIIchYPGvUx2wjzRxnOzNgURxf9yimJ84uxH02aA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T01:29:12Z"
    mac: ENC[AES256_GCM,data:WnVq2K84VHxiEhcQc4axXJZ2P+kEBH/ml0rbJ2RV9NSL7IB4pLJzk3wzJbu99DTbwqGxi6v73Lclwna6R0y0L5U/TeMs5FH9o9GVX982UxiBXa4OHvHx60Np0ibs+pvXNo5rzWS18THIitbmcBMEW/JE6NyjrcrCk9+FwUhwGwI=,iv:v+78f9isGP+bIIm0fXS//A1R2ipSInA4RWzpXZHLmV4=,tag:aUfIzk/LnHAr+tSpLxdSww==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
