# start of Meshtastic configure yaml
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:SeNTB4qZ,iv:A5H1bCPFAE6Q3/M7BHXxRfYZOOxZo+kASbfuvY8hPxM=,tag:NszC7ybMxd9zpV4Ke3tJIw==,type:int]
        mode: FIXED_PIN
    device:
        rebroadcastMode: CORE_PORTNUMS_ONLY
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        txPower: 5
    position:
        gpsMode: NOT_PRESENT
    power:
        deviceBatteryInaAddress: 42
    security:
        adminKey:
            - base64:a4G5cY5oxpNueGSajNKmDzRacraL23VgTvBiHw2e/iY=
            - base64:IJYJKEJg8+Tup3B5Fh2l2I0l5MnmMKvvkRQpzRjYASI=
            - base64:StWJrm5nTQXebsJGILTQPOy/nMjc+Eay7MyRQIw3WTU=
        privateKey: ENC[AES256_GCM,data:x840YW5C1I/R4Aax8SNDiNyJV0g7aaFVObmZ8Tzrkuf+gLHeNLf46xCvovgGJOQQ2PjH,iv:e1V4sspRTgxBC7Hfuf/5zGuxjG7jDuySQMTXugns3Ug=,tag:qzJpsMcD3uE6BIuH5eJQGQ==,type:str]
        publicKey: base64:V9yyBualxNv/b+J7C4cnUijXagzLmggvp3i/MD42hjI=
    telemetry:
        environmentMeasurementEnabled: true
        powerMeasurementEnabled: true
owner: Meshtastic 4548
owner_short: "4548"
# firmware: 2.6.5.a93d779e | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVU1LZ29FVkYvSFBLVjZw
            QWpIK2hwTzFwSG81L3pUOElwUGZOSWZkem5ZCm5tTGRxOEN2ZzJwNDAzRWpZb2Mr
            Vkd5LzlwT213ak4vOG1JQ1RRWFdhZGcKLS0tIDNaNkFUWTZWRzZXdlJkLzZRQ0o4
            REpIZnpUN1JrQ3dhekh0Zzl3cE9VQ3MK8RNaNne3gZXYcB/2Lw8+JHHg0mRMESLO
            VVtAX67hWJrhLcVnHh2m6oWI+yqVcWNjhTQGa1MX2J5S5AuX4rLshQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-08T01:26:13Z"
    mac: ENC[AES256_GCM,data:tk8PX82MURHFuqeirqcBYG2VdTI40nKcuMa7uPyqZcu9r5yk8LoOmCxpNBxrCMTl9CnBasZYhxroMxT+n2SGhSxgx9gdFyBzCRLZBQ7rbbIQYrV+YwVMXAQI8vcpc/uuASzBoL3tyP3rrkdZs4IltznNQWV3AwNWxeU2oP+OW6E=,iv:yS8jeBK7WTbMQRgTUfmW8fAARo5wbXb0FR1/6us7Ql4=,tag:s/SZyjqPLnuzq7OV/K6ITg==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
