# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:vX08rX8SH0X4ImuXBs3gbdFnqdx9iuUQ1R9aiYOP+3PfuEbzBF+t97YZbbbzcnsiCRvvOf6m1TjhpQ==,iv:0fr5Tnw9ScsGaTh670FU1s+Ij5BbY25TozlJTZCFigs=,tag:VOrw/8qvZdCEKuGIuRVWkA==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:ae6SyyA6,iv:UEfx/8GNpS/DVjMHrzHKpJtNpB7kRHYvcAmqnVRCmq8=,tag:D8Pn3nczJLSE4+z1MAff3Q==,type:int]
        mode: FIXED_PIN
    device:
        rebroadcastMode: CORE_PORTNUMS_ONLY
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0/2:00:00,M11.1.0/2:00:00
    display:
        autoScreenCarouselSecs: 15
        displaymode: INVERTED
        flipScreen: true
        oled: OLED_SH1107
        screenOnSecs: 600
        units: IMPERIAL
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        txPower: 22
    security:
        privateKey: ENC[AES256_GCM,data:SeV10EnN+CfmHK6NHlkRVXXu9VsYIxVhVSLjQMoS3kYIYjzAoBXefpVflTjKQiesGYt0,iv:UfDtq4x9cZSICxNSyKv1F4LBABCrNIH3xrFYOg9y7oU=,tag:u7bzktZfU5M7uaVakdjRUg==,type:str]
        publicKey: base64:O9nqwF93rokUlxCOA2Id+Z7Jos5buld5VEB5IQ5VTWg=
owner: pork ikoka stick
owner_short: 808b
# firmware: 2.6.10 | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZExrM3NDa2JOMGZ2ZVhq
            ak5STDZodmxjbW96ZzdKc0VjL0wyc0hzODA0CjQ5K2dqVXNEbkZUaDNkWUxPcmh6
            dlB5alJPckQ5RUQ5Mi9YeCtUSUwvSWcKLS0tIG1KT0dNQ1ZQWUJSWWJINEk5MUZP
            alFoNmV3MUhKNUhuY2JiY0c3azdtSWsK0NGbQPDUP7zvF4XbZ+6XS/xdFNJs6hRP
            fgiMButllPzKsO+K5rqHKsezPjTdnDfzSVNRJmKur5EpuhGcumU++Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-10T03:55:09Z"
    mac: ENC[AES256_GCM,data:PRYbqtkLihDNbkA0dDJsi1oR5o4uOHwd7802OV9JVaPblbv2p/BcfwNk8+CzLR7t0U66TSX6J2/d7k80gYHbU9NyVHoMRj8343XRjdSSmlv/F/NcqzAZ8al902ya9MEzQcaTFHGXoTNxZIWVblXp6ms/PfR1tP9mJuriHA2m0+s=,iv:QjEeXVXVeJ/sMzj8Pp7balXJWrsc63Rn3L/Df/Bpw9Q=,tag:2F9rv+S9xJ+Zv++CnWy67A==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
