# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:NJAx7GOanvlxwkFY5tIMG19YQplPWSup+ToSInZce1XnleXpdntEyl2FWqKIojDZWv7g4onJ,iv:gjy4trWWwio3ZhfmX6cAVjHqrbWCls0Q3rEoXkpk9ZQ=,tag:kOn7/hdB7SJ750pBsP6Vxw==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:8dcOtcDQ,iv:X/M+6glCeUpEjK5uQ6+ET1xtR31dNaHSoa4RbNbhC9w=,tag:TE8uezNyfmAhxXMMuK6m6Q==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 3
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:VYFShAtHu193p/IcSYSj9cfZJZg+MpuimkEuZrLg8vmNo3YPeT6P3FUfw7C++jxcTk9A,iv:E6BkYzABaNZakYWbasDtRmXB3O1Ojwv0NbQIWvb3ux0=,tag:GXJX5G+LBHLw8EMiQsr2Rg==,type:str]
        publicKey: base64:xV3Lt/+i5dXp0eu1APlV8tfUHZXeGS5mPDIN0hUBVD0=
owner: Meshtastic aaad
owner_short: aaad
# firmware: 2.5.20.4c97351 | state = 23
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VDJCaEVXanpvTlRBVDdh
            L1ZkV1lIay9NSHduaWJvSFY4c3JWS2JkdDFjCmk5ZHY0ZzVkK3JscGZ5NFNQSCtE
            REV4YnhVVS8wTWVkSi9NS29samRTSWMKLS0tIFRwVjUzcU9ubTB3T290dWRMNVF4
            dTVITVNjZzRyb0xkOURvT3ZqTFppSXMKvAoPDjSzyF9vfjucmYSrEswJP/JKwDuU
            y1Ul44956GdrjgKaS2aWwyJLwAzvyLH6OVpq7YfDq0JAKyun6D8j3A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T01:17:05Z"
    mac: ENC[AES256_GCM,data:IOd1otNUQLuuIeuzzun+maVJQdsJd0IVrkEQv2AKNMGcoOp4O8fvX4IOBlAykzY30F86/RAtHtWZSso0za5MXiCva5e8gw+jMek22MoHmRbYINNVpEAiKFFFR33irSsFczhkHd7lR0bjVGa71RQIz8DcB4cb9qcj6aLr+yqAdpc=,iv:GtF+ltEJPJCVRvau4009jjuZQgY8NMlrGoe03eAYrtg=,tag:NRRZdjbiVvQj4mPeovvMaw==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
