# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:oi2YslpsMJyiSVu7jxH3NVOXQpLwdsWOH4zT2wwx9mp78apY93HJEiu9FfMsTF1x9uXj5XG5cJo=,iv:tSpHn+N5oMKsWasfJIKnk+NywSrwkxIPoFqEd1Iu/Cw=,tag:3TWnlF3Rs5FXSbZMo6ih+A==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:PS7TevEy,iv:1yQs4H5imYgEky2u32VRXd8pynkBJM8TnWkAoiVP5M4=,tag:bEjkTXmg5vKfJUaEEUNwcg==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        txPower: 20
    position:
        gpsMode: NOT_PRESENT
    security:
        privateKey: ENC[AES256_GCM,data:wV9P29+mJY/8DuzVHeGHN9nd0NfvTAwK5razxkvpVs77L75rwy4PsI1UjJ+7Ste9TWhx,iv:CI+IPnV00tI/dhLCXm4XvhoC8RK6gYiKl2WFswoNwrM=,tag:sSHmw2MxB6S/iLJfYP4QIA==,type:str]
        publicKey: base64:B1bHSftFmvevOhNCMKe9Sb5tZfPUsEcDBJLslk2/oBM=
owner: Meshtastic b979
owner_short: b979
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUWV3K05iY3Y2dFJ3aWZ4
            a1pNTDB1UVJyYTFISjJ5WkxyZ3NiK010a0R3CmVlVGhuY0xWeUdOdGFVYTl6VjdD
            VW5qWWg1bCs4eUVTZERLMGk4VTVVME0KLS0tIHI4Umg2NmJDMFhUUmxoT0p2S0Fu
            RDZ6TlFCZ0E1RkxYdFNwZWRtZjlXMEEKKtOHi4rK0/Q6AT26wh2UV6fTekBk/qoW
            nnt6VxNmcKDgrJnFC81OlMrL+BiROP+4oO4lVFF8pJczg1IxWpWPRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T01:52:08Z"
    mac: ENC[AES256_GCM,data:UE6eZvFD7Yrhj8qZS21hPxcKW7NY0QrGCVEOUi2+rs98eGBivN+SN83cd+EyXzRwYLImA9EZ6TitQYcPyCVKL159JIGUiMGQYT8weD1Ssnu6HJhtOaTO85vhzPtOrGhqNgx/mGNyDvn7wtjaVnU1gi018ajYhSsj2BM8OLJmqVI=,iv:Kya3v2eacn+oyrEr/jTSgljO29+Bw5I+aIdfyvDQw6g=,tag:TpEqSvhKbHGy7+cy5bFeHw==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
