# start of Meshtastic configure yaml
config:
    device:
        rebroadcastMode: CORE_PORTNUMS_ONLY
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        txPower: 10
    security:
        privateKey: ENC[AES256_GCM,data:MNv8VVedtn0KMYa2e/4gfOI6zZm3Gi9YfrbEWyklNKNZ/NDtvNJbHGu4QaTfR8eU+auq,iv:+XtlAliYxa5G/VjlIR5rudSkwnc+O5YDd4v76Erfdn8=,tag:lZ7+8bX4IF3nC14VC7M2BA==,type:str]
        publicKey: base64:CBpOFmbDYVG3fx/qE84iSO6ZMJ+Qss6XvZ8wCtLWS0k=
owner: pork babelfox
owner_short: "\U0001F4F5"
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjbDRBSzZhMStKbU5zZERq
            bUl6Ym11VUZnWjBtbjc3MldBNFZ5MGFidEQ0CkVSc01YemNQakxWU2w1a0hhRnJi
            KzRzY1o4cW5wcUcwUHFRVk1sN3c2SDAKLS0tIDlZK3NpdmlZZmtzVzdodm9yeXow
            c0hJMXRuc0FNd1hkT25PcEJYSHdpKzQKIeqVpao4Q7iye7cj7rknRv6DXQd8Vk0l
            /AjugC8zD+O9pjLexoI35HHkEU4RcIN6vFCPxaJJJhKJxcB8zcRU2g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-23T00:55:37Z"
    mac: ENC[AES256_GCM,data:CS/mRcLeyTpOy+9+FDD3GFvVHnJVvBOCB80tr4SZtKMlsa2ef42jJfTDlAQbwj2IMNAemAaSfvDixiiD1joiRAs+XtTiWfmXnc5wG5nphzWYSe6Mj78OdmJXSM1J6mY0IIIqeWGh12wjgf7Gleg+UjRpsSHA4Uxi1l7maVAbrKY=,iv:3DJKM6zRLhYTFl0C9Zq6nHnZVYzByUIyVWQ6Qc2bx10=,tag:iVuJIDa5J+STi/h4f9Wtaw==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
