# start of Meshtastic configure yaml
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:IGoHPPmE,iv:YtHD3UOmTXNOpKIdOU0TXaQBZz4TjP3H+x2V+ZDsxeY=,tag:LJG0/ogmmmqPowEu4ZTxBA==,type:int]
        mode: FIXED_PIN
    device:
        buzzerGpio: 33
        rebroadcastMode: CORE_PORTNUMS_ONLY
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0/2:00:00,M11.1.0/2:00:00
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        privateKey: ENC[AES256_GCM,data:7RFOlxevYfkJop5R0FnlSDMID1c3qdzJbjvC6CEZubU+cfOO64Qa4+A30zNFsT8dpsO4,iv:8XckLqm4N0IS2PTW3xqGvE7rAlnqlsFRaWfENnrLxjA=,tag:bRABK6QQBJIuCZ6JZB03fA==,type:str]
        publicKey: base64:OMFHkw/udOhddjD0CYKQNQY1nuSxtF4DE6cQCsPRRwQ=
module_config:
    ambientLighting:
        blue: 238
        current: 10
        green: 240
        red: 88
    externalNotification:
        alertMessage: true
        enabled: true
        nagTimeout: 1
        outputMs: 3000
        outputVibra: 33
        usePwm: true
owner: Meshtastic f0ee
owner_short: f0ee
# firmware: 2.7.10.cea9e12 | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUcGZ5SWJhUnhySGVQNzlO
            YXpwaDZKNTNpdkxlMGo5elpNY21sTm9FbURzClRGNXhJSkNBTXhvcWE2VHNxdy9C
            WnZreHNob09vNElvZ2lkanVqNDBEWGsKLS0tIDNGVG8zbjk3OWp6bjR1OTQ0anpv
            OFNHajdlWVFtVFpaTXhkUkN5ckh6MXcKQyYsE3J9zld3ZkdQpga2HByssjEXK6km
            OseYknTXP/fGrbd1JSTgez1uPro4KCE1DuOLoqBhbcJrWA7UhJY6Mw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-23T04:05:12Z"
    mac: ENC[AES256_GCM,data:NL1c/XvvK3dnZUjlHQzDX8lmZWDkWQWoo1LVBlyuNMhqFwD3SNlGLbZ3ewykQoRzX8SxWPAbx3mCH5UT6lYdyGSLdqe5nvTlRqKSk3duZ9CtzK6HJn0rwhRRDNn03Gvr1Pr2AeLTl6B6jDv5WQRNWiPRtLDpWaqN1KoTMc/Me0M=,iv:wZoQ3reOqV1VmcAnVKCbU96JQtFZvTANA0bhvx81zFA=,tag:TLoosMzGH+pBwMADS55rDQ==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
