# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:Fz/CIAWIhObBDbweyrebQ7JP7B9z6upnulQ11o3zR/HG70z9iPPVnX74keYGE0+Ru+02GMp0CrNj,iv:laxF3+XflR/sXFIVbRDIIMWmJReqT/7sYKJ0eWZaKmk=,tag:BP2xXKMnrHK/TG3KTnqg+g==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:Oyb8/ttQ,iv:iJosyY4m4Re5pZJLNsfCYyxI9XhHvfx6XEXdfbQM9Ak=,tag:N9ODRFA9Tk1K1cdA6/Wasw==,type:int]
        mode: FIXED_PIN
    device:
        disableTripleClick: true
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        displaymode: INVERTED
        screenOnSecs: 600
        units: IMPERIAL
    lora:
        hopLimit: 3
        region: US
    position:
        fixedPosition: true
    security:
        privateKey: ENC[AES256_GCM,data:BFD8Zl713c6OxlMx6aBUrV+i2wYhFej8Atrh4waTnBX6P5ox/0/D8DXAlVz6MYI58Lh5,iv:fJf/XgRZ59fkGwllfmpSRSHQdDRM7qWAlOE4o9ZfgGk=,tag:4/uyEBdnFWVLxLpMD9Hl0A==,type:str]
        publicKey: base64:3NqT8FZt5GsJkYOoU7iA1Eo7Bbs+lS3/H5JY5izdUHs=
location:
    lat: 40.71
    lon: -73.9515
owner: pork station
owner_short: PRK2
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYakNpekRmd1FBY04zM2s0
            MklmSGVDbHRpV0RydllMOFdySmk5N05VVXlRCjBWVFhZazNpWTBpRkZ5dHhIZm9B
            bmx3aHhVT1NZaXFDZnlpdTBnOW5ZakUKLS0tIEZ3TVhkczRCZWFzMWdxcEpuODFG
            c3N6T3NLZExMMDJYTGNNWEFPVVUwRzAKprmWrYYxXk/Ve8Yu/4MIOKRfezpucZ3N
            D1zw1AcNdsCE8FwcQ/29WMrhg9qqP7C1GjU5caZOmIp0p8XW4NByDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T01:51:54Z"
    mac: ENC[AES256_GCM,data:Ka7bQDxSFT8ip/5VLjL702PPPvzqsTeNZdyW4t9Pkuh/gnD8lNwoTUgQhsedgxFvTveG/jz0PXpju6u00anquzSwiREb2NQx2+FVaDddMsjdliZEpkyR4XbIhaLNbzjsDf5dS/bOb1PnPnO7xXh883C1KHL6gFV/kqji1a/Pdwo=,iv:vfH66wv6Aa8d8Eg0qzqwA+wVQoX7ugbo8LIjM54Uv9c=,tag:r02SMrIv9qbSPWXzSS3FHA==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
