# start of Meshtastic configure yaml
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:yLk9ESqQ,iv:bDgjAQhpcv6dhB72iEGa1zX3YRhgROA3kAwXIpUc8Bc=,tag:SiJzKJbSikKGN9xN8g7LCw==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:IJYJKEJg8+Tup3B5Fh2l2I0l5MnmMKvvkRQpzRjYASI=
            - base64:StWJrm5nTQXebsJGILTQPOy/nMjc+Eay7MyRQIw3WTU=
        privateKey: ENC[AES256_GCM,data:0gaTQliz01I4JnvWTdSZ1bZlCTGCuAOqLNJeDbvM0bUng067jePQ9fwJcFvQeULNYnT5,iv:z22v4mL+GlSzkOV+42cE5qHQVhM8wTDU7/hiPn3AOU8=,tag:wAkjEzvM++/kUwgWPSRRkA==,type:str]
        publicKey: base64:plCrTmweKWS+JMyclkBUmbT19u7JPZTjxoUjUOcmVgk=
owner: pork sidekick
owner_short: PRK4
# firmware: 2.6.5.a93d779e | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrcU1XSXhaWFE1WmxPQjFw
            cGFZbFRMYTFLQW5MNGpvbkZ3c1YvK2p5QWdFCjVFRHZTa1VrNHFhT3hFR2kzVkM5
            Y2hhZEl0QUlORTlhd2RIUnVGY3pya0EKLS0tIG04d0Z3Q1JHT3Q0d3hKZ3lRL0gz
            bFluOG53Rm1IQ2paV1lIcHpMV0pnOG8Kxp4Cng/+CBNCIXza6bdXVH2dtztmulsP
            vXN0P26R2oae3Wluyrkhdt5aaHdZYFFeqsUqA12/uVylcI16jXLykA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-19T23:32:49Z"
    mac: ENC[AES256_GCM,data:q5XI8Nrs+dwfUGZAjAiIiu5KPbqGvKn0DNTOTvxruvrCPgSWUoZdeEMX/cPxX5Z3rzDr1rAoNU36PfS0spsYxYbP/EY8Zt3lYK7t+pVB9P8dTt1mmTFHgAHO471hkXXFHd+YzCxyoQjj/oyhLexSoTVSpPbkxn6ofSQv5PgGFJM=,iv:HSzcDViEjLZvPoXMuz2/wV0F+by6jZPYWmFJUdSr7YA=,tag:58qQ7YhtpA9/M0NPPfLutA==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
