# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:FJ/Q4tSkNlQGbvZZqCmw2QIyohxMUulWE/mdW9sK+p9/ktKLsPfyCMh22UTQFw9EoHp5sDLMe/DGJaZKU624Eg==,iv:HFVOygYNed/mabM9sJjSs0tYEm/E6h5CqAFVzVdIuqQ=,tag:mFsgkzoRjItIJ8kyTG/ynw==,type:str]
config:
    bluetooth:
        fixedPin: ENC[AES256_GCM,data:oJje3hk8,iv:P5tDcNq0nIVV5Wew6BLrfzhZkdH3MdFkLUvx0w3VOwE=,tag:zFdXh9PIb+89ObzaLXftXA==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        gpsMode: ENABLED
        positionFlags: 811
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:M9Tn9nAO1vy1wJIlbMNmnUbTUIEOyO7CPKs5jcFbDAxSO46EwzrcmianQX2lU9Qbsbju,iv:VmNfZRLNobRwQzEqSyCLiuBODUsEwZJTY1b9xVY6+Bk=,tag:ldk6gngbsv7/FLP6LNKcyA==,type:str]
        publicKey: base64:sp9nI2Fbl6ZX2r0Wy2RcmXkOrfRy3ByCh4K2acwnuHg=
owner: pork tdeck
owner_short: PRK7
# firmware: 2.6.0.0b106d4 | state = 24
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMVY3OHB0TFdvMDF4ZmNG
            R3JyaDlINVpEZWZHRnpPYWZyQWRxMVEyTW5ZCmUrdEtybnRrcUxYc2I5UGZGY2RJ
            cFZObmp4VEdFcEpuYXZ5L09KM3ZjL0UKLS0tIGg4ZHRCekx3ejVObnN6ZktFTExZ
            ZVl2dTNvS20xNmNyNU9JdysvbDBrZ2MK9/vipVfMerxWX4THZa4rKw8asp8ULxu5
            PZFZ81+rcDQ+LFhY98kUuE11t9uZ9rVfwlcjnZIyzGo9MFf8TzcQag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-03-22T20:23:00Z"
    mac: ENC[AES256_GCM,data:5w1RKRyIxrGS7pHoUsPaP9IWLPPocL3S8KuNJLRJIgHzsyd/os7E2MSy4lIP++oKzcHyCCJlYm2lFtTxscr0poQI78PJdi2whFY8KDIcCQSMNy7TX3BW8GQllQ/VZXEsIDGbhgmGu/tkYTxsRINtym5dxh4l7P7ungBm+eQMI5E=,iv:/Rpuozlov2QP7O9G12p02gRwrgbK17VkcgkEi5FrqFs=,tag:SMCF8DTObqZOzre1fBNVBg==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.4
