# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:nAaukz08U1qyi8O38S/35ZmeODGYA/Uw2/ndSySkoRSc0eL++ofmk4DfWvt5lr8u+I61ZaTN,iv:ZYSS1duvOJi65FeXSFqdd1rMwm2PUZYt/+W+rzEqry0=,tag:fXnAMvCO/tUNjHjp1mx9Hg==,type:str]
config:
    device:
        nodeInfoBroadcastSecs: 10800
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        displaymode: INVERTED
        screenOnSecs: 30
        units: IMPERIAL
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:AFc+CSMNtz3gnKqS3FaiROSruVKPX+mogHaLKdQHxm3vCv6dd9MM2Q2JTIOSpR1OZPP5,iv:DTHbGszD+xzHSBm7sisBiV29UoaSUaTs6ZEyOvPboYg=,tag:l/cANSkLWVF0ncIMeK3kvQ==,type:str]
        publicKey: base64:sp9nI2Fbl6ZX2r0Wy2RcmXkOrfRy3ByCh4K2acwnuHg=
module_config:
    externalNotification:
        alertMessageBuzzer: true
        enabled: true
        useI2sAsBuzzer: true
owner: pork tdeck
owner_short: PRK7
# firmware: 2.5.20.4c97351 | state = 23
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTGlST2JDZ0dPZkNFQXU1
            c2hpK1U5Ylp6bTU0Umd6V29RVm45aXVWVG5RCnN6Q040RjAzd0orcXF6MDhXZm9p
            T0habDB2NWd3RWx4bUx5WXVEOXg0U1UKLS0tIG0xby8yZFdpazJlY241dGxsRk54
            SVJDQ29PcFc3NjVpUFI1SjNHaXhPTzAKRZmKgbQLGHP5uhFDjIZFscvuBANfApTz
            TktEPHAp+FPtdSH9gYHdWV0fkKwe+3DqweslGI2NMyr9Mf7EC8aJjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-15T17:32:52Z"
    mac: ENC[AES256_GCM,data:+XuKCYL32OxJWNA1f7OPG2spPnUhgI/V82bL9Bj2GO3wQx55ZA2Z6AE/4oQwf73oR1482qTTuGN+3YbgJTlIrMbzrAg0mabybWZ7hNrCOpTzhV+rgI0+FtC/vd2sjZ2S5WwNqtdIup0lMr6pUp8QSEy+/h5044GUl9q9vm5p4rU=,iv:l+XOLfQOtG+BON8iZ/PmUCPHIf5bUVzp/3TrGY4c+o8=,tag:dfvEH079cA2QMq3wqBA2uQ==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
