# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:eGs9f99HkeD0Osq9ILrzL9dVWVkVx6LFJyT4P3sy6ATeCuFU1+TfquFaGa4G6NIELzS/zmfe1b4+ov5oVg==,iv:HKnOjto0nUCcRL68NPK/oncSASVRJQ/Jd/lYFhDBNo0=,tag:h7LW70Z4FtMu1ob+P2NEbA==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:UwS5s1Qj,iv:Gr8TmZWQ4BU7C2VFu+dV+BybhmmSYsA+W3Qa7LLJYwY=,tag:UWLndcsk9aBFQCB8hKjNHQ==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:evN5AjBna0mYX9hkPdoawxPahfGsRnDPsWocrSfV+pofZGOA/m73Nk69fI7jSRncoTvm,iv:ILRo7RYYZatuucd+f0XM3vuCxNj5GYhdwO57lapXvto=,tag:AkWp73yU+78xf/ufcmFTrA==,type:str]
        publicKey: base64:zXteh5KsAlU2657LidIZMNcLPAcbrw5xagzIcqm+cEI=
owner: pork faketec
owner_short: PRK8
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZGtlZ21PRktRVU9JZlZL
            SlR4bDkyVUdYOEJiZ2dpRTZsK04raU9EOEdnCkZOSVc5cnZqampMdVFiSTB3aUdF
            WkMzeUJ4eFdPTDN1ZEhFTUlFa2RaMUUKLS0tIGVMdXpPMWJTR21ZTWpEalFOT0c5
            T3p2QWMrazBHazBLOXZ1VFRsNnJOU1UKulMGwOjhGm7sGSv6b+JYU9c60eaomfLT
            McflKg7d14HIuiH/QuIyHdphLcwPul2UhQ3jNVLKSUHlfE1JWgbhVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T06:27:22Z"
    mac: ENC[AES256_GCM,data:X21gJR9dqTWZKNvtLSJFAXJTkWH2vyXGIHeIxyPU932ad+K2ypNT7Upq6+baFhxoBIiIrVMo7Js17/jP5jW3CfpNlD2z1j8u8HqnP0Ph1Y0y2pTIU8q3dNP30N1QFXWzN2MZD7heH8sLr54M0Xz5uuz2LOFt6BFmAb1k65gls24=,iv:3IoIY2/W65hqSzKeL96T+500xphdpRiC3n/KhVoJ0Sk=,tag:meIKd9HNz/t8+DaW38IL7Q==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
