# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:/5MURSYHICXAp1H/sV6eHHAIaIj707htB+ZIYDGz+N5JWk5fUV4qpEpSjQoQmUdJxy3DAl7vOpEGXw==,iv:WGcYa0+zfeYuOFFaWsdiDxqx87OTl41LCTHigt2vNvk=,tag:X5hgcc6WadCkU7va+mYBHQ==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:pzMLIvty,iv:YsixXrAeMDIxD/R00lWan4pfpxhBcJHCPpRsHHlrOpY=,tag:ZRGW4+d475WMwNGq83yNtQ==,type:int]
        mode: FIXED_PIN
    device:
        disableTripleClick: true
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        txPower: 20
    position:
        fixedPosition: true
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:zR2A//a7YID3hJZTfJRJ54NS881XLX4X7/dCpjxgRUeaCTAbrP3CGt4QOOKT2qseKRdG,iv:qtccKpBYyMm4DUBF6fpoRMbSUQle/E4DtvpM7OGBeOY=,tag:R40Ee0jO2tGwb1JOXvD9Bw==,type:str]
        publicKey: base64:77X3Tnk2u9QHdVUzNVeVdw5QO9E7qv7+v1ikFkkJrjo=
location:
    lat: 40.71
    lon: -73.9515
module_config:
    telemetry:
        powerMeasurementEnabled: true
        powerUpdateInterval: 1800
owner: pork ikokananov3
owner_short: PRK9
# firmware: 2.6.5.a93d779e | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIK1lKVFoxZ2hkQUxqbkZw
            V0FUay9GakhTcVAzZlI3UHlmV0J2WHU5ZTBNClRrU2lPdnZYQUFla3RHSUlqTnhQ
            UW85M0RiYUZRci9hNFpBcEdqT2V1czQKLS0tIEJsNWNFaDFWK0dIYkZoSW45ZHZU
            K053ekdyaS9qZW5na1hDdnFNZmRmV0UKtAfG6DdT0qOv6r5A34ajEQYoMRmVqmlI
            C1YVNJGRsFnQCDZEJB53PcuwiR3wsUElP/Vt7USeIdmL5apP4J5Rnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-12T00:46:21Z"
    mac: ENC[AES256_GCM,data:tk6YlhJtVAwV1xqGts1sT8gUS0UML2KagVBoiwJXz3p1+qV4uiltDQqPCNXPP4yDCIOoVynDwNg+5LS2VT3kqB4Bxx73BFDAN+UxHOlLL34UTy071vx7d5sp/+49lXrcRa1oazlVfHTpU2/ygrlmcuZVsZusvARywc/Q+wxquSM=,iv:PAzpGE9LDcruiOUTr/pEpvG5dJAl7UEd/Muesd1/woU=,tag:Ufq711WjhNJR1Tz4Ee6+4A==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
