# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:GcB+bdizjRcQyHyXs0jBXSg+fOhdCwhzenfLMLzNIAgoilb6Pv3NmvR7q/Fdy93RpKsfymSKOFsl,iv:OUkrNXqnGeUlMlKw3R35B/5FfiweZHAZgKQesFVMyl4=,tag:40XBD3T4RtTPLdIbFpMrug==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:BDQxLLmO,iv:9Kismj+5ZbJPXbJFvLUsC6oBqWRE7Y9Nh8cD9KrCBKY=,tag:6y2LfX1EmYRoODn/WflfMA==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
    lora:
        hopLimit: 4
        region: US
        txPower: 20
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:liKotS4+X16mVzZG0AmOvyGiTc7RXmmphM+jcuhsj4Gsd+yU00i0mbMx7wbOiJ/+Wwn7,iv:hv6ayXMELO7+R3+e8f9eWRLL8TSKTQcD1C5KSZbzPCo=,tag:DBA6rGB1+oXxkrZm0mSeag==,type:str]
        publicKey: base64:77X3Tnk2u9QHdVUzNVeVdw5QO9E7qv7+v1ikFkkJrjo=
owner: pork ikokananov3
owner_short: PRK9
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Zmp1WHJhVURDeHF6cVRF
            Y0JXbUdPQU5lRk12SW1lTTA0WXVzL0ovcmp3CnRjeWVFM3h4R3ZxTXBDanp4Z21y
            U0pSa085RTNyTDdKSDZrcGI3aGhhWmMKLS0tIFlzUTNCQS8wSlhqRjRBODRRUjdr
            dWhXbEJ3eExQODE0bnMwOGIyMENSY1EK4tgHXseOl//mVb+4CuOKzrMbQkUd89vb
            WTPEosQtHVBV5jCopPMvOP7glm7pO5V3AecNcmOoSnvwgDf6vQB0KA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-24T01:55:06Z"
    mac: ENC[AES256_GCM,data:qt5jkZHi88YF7Q7l2sqswVoX7mS3WfxC9w5rOw0kZNGA5tlQIk7cnaJcEtFar4DLBPZrqudN2l+DEqR2a+LrTNBpWimEFVq4vkwMyVusDGl9Fceq45nfeCGW1IIE9LfmREEgkLCageOqDrjrzVgEnc+CK8E92aRXSTB824LBtWE=,iv:wFAU/6ayamSGYqf2Vo/Xr1KsJc0QSq98WwLkslO/TQA=,tag:X7vEci9Ei3gWvcwPG7tbdA==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
