# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:T1n5mcXd/OLRlgDP+NhXjEQMAOomLsSkR3kTFy5XY++fE+RbRZChg+/4yN/byUSA647YilfVv0lUnQ==,iv:ME99C+0Yz+hogkVExE9lkmwmrLDKofnVSQAddHZccCo=,tag:9uXE1oJCF0DemmyWCv66qg==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:IV22Awd8,iv:3tmnoRxl7cHSJ2ABI1gY2dzHKixmLc27Z43iLi266AM=,tag:UICYYsmMRFYkXXh5LOfM3A==,type:int]
        mode: FIXED_PIN
    device:
        disableTripleClick: true
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        txPower: 20
    position:
        fixedPosition: true
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:gP7i80nLcbcIpVbUFPgAS0KsOM7PDq7dHIeEi/QvfQVU8EFrotwaPYL1dFo5pxzyJI5e,iv:0x3ST5CmT7Opns6buqFkCG/2db2ry8i9GDcS7DhOTQY=,tag:1XslTH/RdjdfrU5wCjB6gA==,type:str]
        publicKey: base64:77X3Tnk2u9QHdVUzNVeVdw5QO9E7qv7+v1ikFkkJrjo=
location:
    lat: 40.71
    lon: -73.9515
module_config:
    telemetry:
        powerMeasurementEnabled: true
        powerUpdateInterval: 1800
owner: pork ikokananov3
owner_short: PRK9
# firmware: 2.6.5.a93d779e | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSd1dmd1FlaElXKzExbXJN
            ZlZSMEJpbExHRzNYblFYa2xKNFIvWldncVdvCkt3UzNUVHVHRUZmWW5iRWRtVlpM
            a3R4UjhsUXMvMDdvbEt1aTVhc2JqdTQKLS0tIEJWZHdVcWpsV3NNUjZsVkZSQ3Rv
            YldQTzk1QUh6Zy9PQ3VaRmNwa2ZJV1EKEYw55KUP/nkSAmJPHLiCIK3pr6xohbCI
            AauUqpY+zlrfy8UEJW0wkd7rqkb3Fcor9b+Ak5gijY6cjfKUWJphUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-04T18:12:19Z"
    mac: ENC[AES256_GCM,data:IzfGmeiAhiItN/urGl/riPFwdOzPVSWf4VXvLBggfK7jP4fmKYdcNQ6XWZJre6r/kS/zmYsp48Yb8AEDmamx4SIuIYRLWU9+XUa+dT+9umuZh94oetcwGqvZwIZAcnE3SrRgf5Mn69q+0PXU2Mp54Jiv3lU8WhU21RF2OvDkBTk=,iv:e1oIux7fGBNRZFG+Bh3z1y9u9tZapYqi9uvCgksp8l8=,tag:p6SLgZxKgNdtDWHI6Bn/kQ==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
