# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:vBApKcon6OYtGYFsXoxxuYF2kgrL/0fgHw8Hx/hE3Sa4wCTXMZLtTFHSoNsJMg1xxZiqSlRf43KmKQ==,iv:Wt8fqOG6P2waYt4wBed+OvJif4aNWWicb9kNATw6FsM=,tag:AhGPQkkdKggu3ZirBxy3ug==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:ckb/Re4B,iv:qhejfrgXZ3wCuSCXVutBGBw4jomqQobg/37S4wAZVCw=,tag:mDKYcdCTDvmRAD+R7YZAuQ==,type:int]
        mode: FIXED_PIN
    device:
        disableTripleClick: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:3NqT8FZt5GsJkYOoU7iA1Eo7Bbs+lS3/H5JY5izdUHs=
            - base64:Q6bVoME8GWxqsTdmZkZDXB2T6IR18ret860spPZiYB0=
        privateKey: ENC[AES256_GCM,data:lSuRnpOzxd3BzHASoK9ubKdbprIl/zRpGf4rvlqRPQoxI0INh33tGy+D/eeA6Xn08Q1f,iv:eg0kalSqm33VOfleV2fPBcW+EfoGr+UmZof958Xzc2g=,tag:IMkdOeAijuQLBCWiUamkKg==,type:str]
        publicKey: base64:omT6MCOmhjk9cmngMRoe9MN3KZi8inDuIqZ0m0Al10g=
owner: pork spearmintastic
owner_short: "\U0001F331"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMaVdVVThIMEFtT2hBWldk
            ellHUUVvaUFQYVpRV2hWamU2UG56eDQzNUVjCmdNaVhOc2Q3Q01TaUtIOTZmTThp
            MEpKRUsyMFoxSVZKejE5K3YwRm9YTXMKLS0tIHBDMGhPRDdnWlI3Qys0N1F4Wi9x
            Wms3UTBqZGdCWGhTVFNoeXRmMnk4dmsK3wNbbVt0bli1T7OECnhEc3FtToLE12Lu
            mF+E+5lHPdN1tZZ8T8EZvtnHdzoJoZ+/eZXg5kny4rS8+oD7QrycqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T01:55:55Z"
    mac: ENC[AES256_GCM,data:rRKImDkg2Qa8C/NI3RBxTp+rBAvSuLjbAqLEFujg91geOoLXuFCvW8SDb338XTNk6gaPmsHSxZeATlpNs3pr6nbNCCdKJ1cOQydGQHW8CpqMi1ao7kFFrl13fua+61hllDXAa1oayhZT9SAsK/Q0e4iyaCTaapW+Dbkk5XH0awA=,iv:XUTWnstauaLHVsfp2QWjM6G4RJNZKKZgWCbxvKTa5OM=,tag:z3D0FEY9Rs0OAz02ZeTWIQ==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
