# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:N3OhzzcU4RGuVPlYTxgolaFzuacDarxQhExv/olSelN7wOQ1zZjk2/1FVeiLOrOtOFgD+m57,iv:M/j3nESMfmagDTn4VWSXXpuoq7hr0JAwkOIKcKZmAaQ=,tag:OeqydMva3NbsnFhE7pgOGg==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:fyiUy8GA,iv:NxUd1B/e07dUROnbhLIUQS1Lml3AlnctkD2NPr9M9WY=,tag:7wIECmCOBwBDK/zj9FBg+g==,type:int]
        mode: FIXED_PIN
    device:
        buzzerGpio: 25
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        screenOnSecs: 30
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        broadcastSmartMinimumDistance: 100
        broadcastSmartMinimumIntervalSecs: 30
        gpsEnGpio: 43
        gpsMode: ENABLED
        gpsUpdateInterval: 120
        positionBroadcastSecs: 900
        positionBroadcastSmartEnabled: true
        positionFlags: 811
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:3YkdKf5sJjzdf6PH0dScpCLpXxe5evTAtTMXeHsbCDk2u0ysu1jkXKf+E/Goxn85DnRc,iv:qq+9Mw8Piv8w4oS/e8OH07UBfydMfXqungNGWbhmNjY=,tag:cEJss5PBdkq92zglJnximQ==,type:str]
        publicKey: base64:IJYJKEJg8+Tup3B5Fh2l2I0l5MnmMKvvkRQpzRjYASI=
owner: pork T1000E
owner_short: "\U0001F371"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2TWl2TnRFYkdkcHM5ZVpz
            RDBQM3VZMlhRNkYrQmNURkxHMkEwZmtrYVRZCjBrMFZXTTd2Q3BNN0IvdnJzRlNv
            aE1WMEVQUUpQMnRGKzdlTVVPT2daY1EKLS0tIHhuWTd1Y005WGgwTm12YU5udmtu
            RU80T3UvdlhvYjN4R3YyU1dMMkozc3MKldf7j986DpTxJIQqhDgBpnhOf+ioArfw
            ck3jJYG5ZEYVfEHql70J/mVQADjsQot9tCnC7du6gY1PqAj36AdPyw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T01:01:40Z"
    mac: ENC[AES256_GCM,data:pWguwNCXbiTlfGzyNbya14FxZgnrbMUjgjUcIaxDYoaHxGCOHje6jKlH8lZXwMLE2M+IT9W+T5uCUWNmEOAosgqrqAsxb6VFXMFLLKDEckcyyU4Ztrn2Wmfs6wjYYz001vmD3igUAiyzjKfRdNu+h9P9AlyUn5cZUMIjTXEuTaI=,iv:4NeAIMWZm9ObTgHQYZCF+sr8v3e91bXXmH1ppmd+ySs=,tag:ooIwnD5du0fDsErUCyu/Iw==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
