# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:V3FkCse9v46axQvakK9LekO9Wn617WPsc8sdX6HsGJslL2DmPYB9cbiH699gWjXWaG/lfGF55tP2UFvQ4Q==,iv:3PUq/xp+3UncVJSIsY0JOD25Ck1wcLChe/MezUkx2/4=,tag:sdTbbGc/KdH1OKhSAKZRSA==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:AviQ4Do0,iv:6IGeEjUwhe5WIJxeSKucLQ2HL+d3pCrWbO2vnadqqPM=,tag:Wpq3zNmKNOmXzy5K2ip5KQ==,type:int]
        mode: FIXED_PIN
    device:
        ledHeartbeatDisabled: true
        rebroadcastMode: CORE_PORTNUMS_ONLY
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        screenOnSecs: 30
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:3Jn6HfuSxibLwVU4w5iIDUsOksc39w2VppLfhg3xQXS8IiYnIGoYPSiUQ7jmoW8VrPD/,iv:JIXtBCXdIKJhDXkBIOWwlY9NilbNOTSGpAalI4lfNqo=,tag:tgjQVEXax4TDoTN0cQIpMQ==,type:str]
        publicKey: base64:EsYn63PDKPZPp3jJVpN5FohrME6SIG0nZHVe0IU95Xo=
owner: pork boar-d1
owner_short: "\U0001F417"
# firmware: 2.5.22.d1fa27d | state = 23
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTanZ0ME9BcWZuMWRnWXMr
            eWZHUnJIVHBsU3diSGlqZ0R6V05lZ0dMMW40CndJdzVEWTZYUTYzRlRnRmxRQlZ6
            WG5KYm1GZ0dZNGVxYTl6bVVDdENlTTQKLS0tIGRvTFo1V1VEQStOdGdGdjIrVXlW
            OWFVcFJsb0hneTg0b0R5b0VIcmk4UjgKn+fi8mPPR8hASh/5u9/WvTLe9mmIP258
            06qCocvjkPsTFENbZFllviPFMUOqae9iC6CjaYQuF0X2P0YE4VU5eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-21T16:49:10Z"
    mac: ENC[AES256_GCM,data:ktEjaFfcvle/W2A3TlqlqlmPf9mEcD63XnMy0FlgIXp+33q5DMhy4OWTukvNsB2JMMuhLuP3/vKL7pziQFRQf/T02GLrV2A/3/Y97dTRMizcNqkuubvPBzWbblPcKE6zJ82qyMbAQD5YjlSu3L11KV7dwTnkQTiQxxPQ7TBDcNE=,iv:j5o2/1LAmlzR0MDeSTSWgJ5jg5vLrNEEY46gel4CnMs=,tag:3LrOJklLj8zjEy8kbQk+qg==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
