# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:rc01mlACkpVCe540Jn2AlzgOX/TkCoNLmDv6qzE7ANR2NSOQ7LnaFKJPjoazSGUcpYA1M/ze+QL/FQ==,iv:C6dGX5eVEjEh3XMW+OjKAJydCdjQ7JtRucldrSEN0q4=,tag:cm2qGGyciyKWzi3ftd4Leg==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:7Or1kQAG,iv:oxSo2TMuDAZof6SExrGuWqou+G0oX2sfshRoKen9BVw=,tag:r0OgZCvm0kr3Nw0NmBCfOA==,type:int]
        mode: FIXED_PIN
    device:
        disableTripleClick: true
        ledHeartbeatDisabled: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:Q6bVoME8GWxqsTdmZkZDXB2T6IR18ret860spPZiYB0=
            - base64:3NqT8FZt5GsJkYOoU7iA1Eo7Bbs+lS3/H5JY5izdUHs=
        privateKey: ENC[AES256_GCM,data:vA7fbMFUeZrlVD+D4TeviQPpsLoHkd5vsWubo0B8HMCjl/S0v15Z5E6XG+sc34/gK4Oc,iv:iVLV37L9dNeR6ZCxf7mRUcSkW+gwmQe2tJT/20BXqow=,tag:r0ugixSoEK+s42xVf087Jw==,type:str]
        publicKey: base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
owner: pork p4gr
owner_short: "\U0001F4DF"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhSnBFdnVOMDFwbFc4RzZR
            Z2wwU1ZkK254SHVCbEx5Nzd1MmVQd3BUVFJRCnRPQmMrOE02SDlpM3pUa1NEUFJH
            Nmk0U3Bqa2JSTUwxdEtMd0d2SkNVNEEKLS0tIENVYW9LSXNGZVI0eWZkY1pZLzFD
            Vno3ekZIQXptUWJIT0FwU3BSd2wxcTQKZiZRDI0ofdHFN6iBpQM6/KKsLvBMoT3a
            z+hTc9kGPt82YFNBHw6/W9Qz8ZVCXAZkuCsB4DvmTmUipVAca4PLEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T01:57:33Z"
    mac: ENC[AES256_GCM,data:bsg+TAkW13ZpbaKY09ITQccKcBnbtWYOQXoaq4hmZweMEOiCYIwOMHnoImTlkouk/nSBxR1DKSPOR0oDFYqahIE/dg7jp99NTky66cP02c+m+MZ1HO+J8Y4aF+QfAcaBNyeQDos2RAWWK752nDdBj400ZU2+Qhx1/sR1lssrTn4=,iv:n+Gu0a+4pu9DQBzsjf1TkD6Fxmzb0Y6LRhLcBf3b4Xk=,tag:Ce6Pww1E5KLBozLLxln4Gw==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
