# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:w1OZzFXvE3uVQ6pN8yjU2xL4r8pB0MwsV0n80V+AZBSQ0kOQAdv+g8wtlX8IxpEupQNR18GFCqd4QeZ1Xw==,iv:l0VYADA+LJxJ7Lcuk0leko4T7z0GO7taSaMc9OHvYvo=,tag:1FD0iN0G4jQFc4SKhq6l5w==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:aLtHMIxK,iv:mrNpdyEcYgHqKjx3tYTFeewNA1DKFWWDnFW+D6h1cu0=,tag:qXQSmIDtb4gjboO6HbRrqQ==,type:int]
        mode: FIXED_PIN
    device:
        buttonGpio: 31
        disableTripleClick: true
        ledHeartbeatDisabled: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        displaymode: INVERTED
        screenOnSecs: 30
        units: IMPERIAL
        wakeOnTapOrMotion: true
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
            - base64:3NqT8FZt5GsJkYOoU7iA1Eo7Bbs+lS3/H5JY5izdUHs=
        privateKey: ENC[AES256_GCM,data:AHTewIqnXOq9cDOLE+4zx0uN0TgJeLcOSQfjTiboMneVsEu7tnuEuvcNDxbERlebRUeq,iv:g0E5XVbE4i2fIrn0xuFpTzeEbThTlmMDWHK5r+TuqFM=,tag:kne3BpaBxjoX/MLa1kYvDg==,type:str]
        publicKey: base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
owner: pork mobile
owner_short: "\U0001F64A"
# firmware: 2.5.18.89ebafc | state = 23
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeHFUdytET1EwS2RPMFN3
            bjdiT096eDQ1ZnVqNXVhYzlBMzFSaUVuS1RJCm5vRG1BZFc2V3ZZRFlXaythM3la
            cFJKNThSL0RlRjRpTzJ0S2h0NTFVd2sKLS0tIHkzVGhlUUlRM3BWTmh5djczdCtI
            T0ZhQnNLWkhsbHdteHp2SXh3d1lMUUEKRCxvd2MVaihcfJSMBTJhxAcIYO9IHu1B
            2MmrNM9+kT796tG5B6mlCvklo/f5Rv2jed/oJn5Xe/tc8OcdRcVkeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-27T00:55:13Z"
    mac: ENC[AES256_GCM,data:IVNn3LGkYBX00UGN1cCC2DnE+Ex8jmDgHApryrGDG7UETQ3zeIX/9RXuw0331DDCUFda5nhudvyd0e2H/mozuKLqVCLBPXxBsBt4iXf+se2ybBNAM+/ItybrnQxUaozIdkUm+aOnNiYEAOXsH9oDXrvQf64eHb0tnTZ3avZbRy4=,iv:01b1wn0MR6gfNmdzrVyXoOYtuuPGtGzGq7k1mgk6rrc=,tag:F2RzcHQXYBrMLfer6xSmDw==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
