# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:kphDa7ziJRqSQJ62Y/e4n1jXEpQd9i8BsqdZrwVUODI8wYJ1DwTsH9v+s4qzqJiGdmb/byO0puTDPcipxg==,iv:F89EDWUau/YRSshqs6jr222W8OP8b5e6je5bf3YiOF4=,tag:9FsYaIWIlcHRekNeEH5gaQ==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:6HA5UNh2,iv:2LxDbbzcIAgBeyCCsv16m623ZYqiwae5+i92DMmLziY=,tag:TR40xmas+rSR1FYactAQww==,type:int]
        mode: FIXED_PIN
    device:
        buttonGpio: 31
        disableTripleClick: true
        ledHeartbeatDisabled: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        displaymode: INVERTED
        screenOnSecs: 30
        units: IMPERIAL
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:o0zw4By2ZLkivph8AWhCd54PcEARMBqpWRznD7LRpwwQgRKSQujHxNpnHooS+vYaAbGM,iv:yTgOplwzZ2vN0djWzqHwHzTb6Kmkv6J0X8ePAi9U84I=,tag:MDSy/F7Nshf5rFuVvi7LXQ==,type:str]
        publicKey: base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
owner: pork mobile
owner_short: "\U0001F64A"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBaitBMTk1eHJYOGVwSXQv
            TUlvQ3F1ZU1jb2hJdFp3a2JHcTM0MTRBNUVnCnYwNmdtYUxZTWhSamJiL25sT0hs
            Z1lmQVZwbFF5dFMveUZOS3drNTNQSncKLS0tIDVDWXk2aG14OGpEVXkwTXZTSlJv
            dnU5UkNmZnlRZjhrd1dqUG9rVUN5aUUKWdAV4+YoEGG3M4lWwz5m36QeI1Irq++g
            xvb0giTt6M20cMN0ldiObvkTcT8OnqLgIPmlpIcT6SRmk1VXXJTMwg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-16T04:35:49Z"
    mac: ENC[AES256_GCM,data:Fi9Bc4YGAZBJ86jGgpIHZp0UE9u3tIucFrpm1FZlIdY1lH4AM+kgPMs4w5zB++DRfWKLpjXrWzjBWRINv9FJM0sswjUPWHIiN1Qk9YrycbTGc2IS7OkCPWhVtXTWgVMErd0Mt+ZaibgwRqKwKdHXZH0iOwQk5M5mN+hQsGOdcQ0=,iv:BDoaWBEMuEddxUzVKnDa0p6JZOEufHfdFp09v4IHLdQ=,tag:mUV4fYP6rMQffNaXDAo67A==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
