# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:fcKTK1EmcTcUwRe+xoppA/BHKY7hI8hRg3boo30dMqbQZAulWDAPhO6CdTsVl6RGAdujJF1jMYsnyyWGdw==,iv:HvLSDDtBCF4vf6iJTU3fEXKqMzIneNmjst6cTxr9v8k=,tag:8+ry2I/OOWUPq/qZc74uXQ==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:p1+Y9C4F,iv:3oMeKRFJfACGp3rMXaCR9Z15X61HH3gmj3U79umUuJA=,tag:iW+Z4FL5of4iEM88ijiFVg==,type:int]
        mode: FIXED_PIN
    device:
        buttonGpio: 31
        disableTripleClick: true
        ledHeartbeatDisabled: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    display:
        displaymode: INVERTED
        screenOnSecs: 30
        units: IMPERIAL
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        sx126xRxBoostedGain: true
        txEnabled: true
        txPower: 30
        usePreset: true
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
            - base64:3NqT8FZt5GsJkYOoU7iA1Eo7Bbs+lS3/H5JY5izdUHs=
        privateKey: ENC[AES256_GCM,data:CSJHI5QsrxYTiPKmc8QLqpGQ3XzB8+vug05Q7hcUKcp3hYY1qV00XHGXgMEVXzAXa00p,iv:I5vswdOcx60QAv2HL4Q+9Feh7/L+2DyNwvR69xza5oM=,tag:M7LM1Tdra9BDcS/YNy3Mcg==,type:str]
        publicKey: base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
module_config:
    externalNotification:
        nagTimeout: 60
        output: 36
        outputMs: 1000
owner: pork mobile
owner_short: "\U0001F64A"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrejV6VEdTZDNZY29vbHNX
            TXh5UHY5WVFtZk84T0hES1RsSUJvREZIVzJBCjhaYUdpQ1JGczZzNGJtRUdUVGpv
            RlFYY0tmb25CZnFFL3ZZa0UySnExNEkKLS0tIEJocml2TGNORnM2M1o4SEgxbVZz
            OFJaVzBDb0FTaUV4d3dWM1F5L0h4ajAKDF3O3+MyfqRlhXmj/XhlPpiaJAjsf5KK
            az3ewM4+BkfoGcsRKwrzoQ+OBMLK1z+D3o4rgx8Z4o21ASJLiEtQig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-23T00:00:49Z"
    mac: ENC[AES256_GCM,data:cMLZt59A+fQ4wvg6f2D9yOmP7jIeRIjbmHjx5eWmAEOW5eG4sucCu6M4pOxZ9F3yUNPswfSOznDxkuWlfbSuTcXpNqdYI2hpwKQYAJjrAAbr4EOivXro/fI/jq0K2keI7q8KDQHIpNk2O0sL8xTEdQZ9mrl8rfqG059dgTHnVKA=,iv:jsUGuudH55WZ5tm2FnRFC0nPnoSovMo8XJCMWaFlSi0=,tag:UPILFZ4mAu9/0lClTFCk3A==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
