# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:Kgdj7Bf7jjf6ins3IV6bd3MZDBf9DoTlcmWqkJlWluUQzwg4ND1H3GXganqICbKMY+ATbJszfdJQWsnMSA==,iv:bJeQzkaYk5BJMXH7Ki3Ax1fDPWNGoHWEhY4ZBNzsRgs=,tag:y898+MdzECMB+TbRoU7CwQ==,type:str]
config:
    bluetooth:
        enabled: false
    device:
        rebroadcastMode: CORE_PORTNUMS_ONLY
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
    network:
        enabled_protocols: 0
    security:
        privateKey: ENC[AES256_GCM,data:Ca+ZE7IAhJ/WtLnxkJo9rU7fBm/wWfAJ8kAIoeXu0HD81GNjUdi+NWnKsg8UVD9etibd,iv:smq0eaXQ6v46CMPBzvgaPZZoOo4HWh9X8AJM41792Hs=,tag:TEYjXaHYmqbcM77MRwgcSA==,type:str]
        publicKey: base64:i+4ad7A1eckiFxnub1CYO9EGkHBtxy4YJ1WtMjJuHVw=
owner: pork ultrafox-lyra
owner_short: "\U0001F9BE"
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMU3NlU2RPM1dVVW1QbkFS
            Q0NlK3pCNjNaenZiRlpxaHBwUmJUUzh3TlJRClN6TEh0SkROejVVMENZalg2OW9n
            ZTNFMG5ZOGRxYzhKOFJtUlV1MUlCd3cKLS0tIE1sSGJkenpZeHFLS3liYmZ2YXN1
            REQ0WGNuWDNlMWdiNlR3YkhqVFR3YzQKxkPeLbjWSV1kmAuWTOn4tG6Nfim5qspA
            +Zif+Ubikt+C30zXGiEmLq/Kvw5KpJlsd0mQubW6KFOHllKlPD2sOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-19T17:33:18Z"
    mac: ENC[AES256_GCM,data:K23xvHnH/E+xPrFt5tshMvM/icv4tFTQDOem9wQhYFIYvVZkIPKxwiH0tTkasong03GZJ7BvcbvpLLIjJoccfChnlY2xY5QHVLo1LWRrb8dob2+0Xhoo2Dzu//Lzy/AOHbrqmR6jcnfTsHCokLwOlSGzFDbaFvOEpFYOIJG/owY=,iv:d0Qyvc1M4WfHreWoSxbLOLOEtLDy2M58qgsAv2g/qZA=,tag:zAXHJFt4Z+b4FYrlZNeSpw==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
