# start of Meshtastic configure yaml
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:v4KS31ha,iv:ozBiV/lpILVt60+DptT0sfUR/fWt+4OcjC44b4LhJMg=,tag:KIddOEbcdK2GKIzRZKBcCA==,type:int]
        mode: FIXED_PIN
    device:
        ledHeartbeatDisabled: true
        rebroadcastMode: CORE_PORTNUMS_ONLY
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 3
        ignoreMqtt: true
        modemPreset: MEDIUM_FAST
        region: US
        usePreset: true
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:IJYJKEJg8+Tup3B5Fh2l2I0l5MnmMKvvkRQpzRjYASI=
            - base64:StWJrm5nTQXebsJGILTQPOy/nMjc+Eay7MyRQIw3WTU=
        privateKey: ENC[AES256_GCM,data:Tf3aBz48C+KYQwqdOxTQna2ggOT9p3XsVRg2stDobt/7l74IR6MDFrsMO1Aj5rES1LxG,iv:AUD9G4AtiQkpMZUW0U5ne0RbNT9+zpmZgzZMlOXkmNM=,tag:GDKy8V34zDJ+px22/ALcLg==,type:str]
        publicKey: base64:DVGf9sQb2wj5/v0AkkOB+kNgtqJyi7Y8h0bwCHKPf2g=
owner: pork koishi
owner_short: "\U0001FAA8"
# firmware: 2.7.0
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ck9RUHM2R0IrNVJhajFy
            eFRIZVZkMHN6SGhzNWFvTGZnNjduMkVFWG04CmNxcWpxczVPdGhXQnZrMnZoU1ov
            cmdaRSsyOVY2S0xOT2JibkxHQ25ISDgKLS0tIGdOTDc1NlVVcytCVy9XOTJlb2xn
            a0VWOG5FNUZldnNsUnhSejdYQjAwQmcKtL0hrYekYHFDObXcaTaYxmntHaPMDwko
            2WYPLdq7TQ1/eLeOANxPS+EfEbZTN/zeGANGhZqnh3TYB1exp/NUoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-01T01:15:49Z"
    mac: ENC[AES256_GCM,data:fylwLA2OD8AmFgRW0MNMfP+oy0Hn3L0DdWuHJ5bTKvQtbUlzZzxylgwCn2HDEIXRcwaJbdzivC+3mZrJrf0kStPgInRWicQp+4XgM7F6p8XT+SAx0geeNmYTVe2A3LHZ/trgg6KeU8/J73vudUOwc0tthvWbYDqesYm5JhVsY4o=,iv:YKEvYbrWv3Y8spsrfl4wI+bohH4urQImFskcSzQr14U=,tag:GCaswZaw2ySfo8WF09Ph1A==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
