# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:1l/8mZ65WabEBFc6DZhnGWBeILQdFqB3ckj8FR4QvuJYT8+4fWFUSWLyaKesusJSpoDOvkh0mvYvTF7TlA==,iv:c3Pi0VDCKwf1vR2eeKlXnI/C3JHt/Ik7vpQciZ0y1D0=,tag:foBfkUe34YePDkMwXbgylA==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:ZQEaMnfS,iv:Y0G68Bh1fTuba9uyCyKU+kNr2QCiNP5Iw5v6dSkSeSk=,tag:PJdrEONtflxrnd+TQtM2MQ==,type:int]
        mode: FIXED_PIN
    device:
        ledHeartbeatDisabled: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:IJYJKEJg8+Tup3B5Fh2l2I0l5MnmMKvvkRQpzRjYASI=
            - base64:StWJrm5nTQXebsJGILTQPOy/nMjc+Eay7MyRQIw3WTU=
        privateKey: ENC[AES256_GCM,data:z0fjKFk6hqurxXxNvMIQIWfywKOtZMM8uCn6ye9JdBVDNbj8d/3GOf0IcUQV3D1/i4if,iv:OZuZnbvzFjkJf8fSmL0PLl6JUWr/ywBhPsgSksFsQ4s=,tag:ctOl/N38f4sWjvwW2UvLNg==,type:str]
        publicKey: base64:DVGf9sQb2wj5/v0AkkOB+kNgtqJyi7Y8h0bwCHKPf2g=
owner: pork koishi
owner_short: "\U0001FAA8"
# firmware: 2.6.5.a93d779e | state = 24
sops:
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQUp4b0U3TnFzQVkxall4
            bUNMYjJ0NlpGSjR0QVl0WTdsQko0S3MzUFV3ClRUNXRzT3RKU0pFOW53NkZPaE9D
            YU5HOGd6MWsxSmVtOVRlMXNtMmlZYTgKLS0tIGd1Qi80SjNMZ1FaV1JmVmEwQWZt
            alM0UmNnSG52VVhuWUJzSzIvVmtuMFUKl9YfyMHhd+U0ugqDjkvmXUXKFRBve9N6
            swReZ5lNR+F7Wt16wn58Y+eoKIxZuprttjEn4qqo0IVHw7Y4/SxHyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-11T17:49:18Z"
    mac: ENC[AES256_GCM,data:6qoi/eRikNJuykzj6paPiWsZdOee4sv690hH2Rpgeyd3OcrAvRuan9eOVnXwt/E9JDp4HLQsFHmY5ELeynDofhUPaZgvIbbgzfDC4paaklSoOmOxISSt9J0ZuNRta+Uoif1Kn6/s44jIAja7ZiUKt9AFH8igxALqDyeghluvy4I=,iv:/yP6XN6sioPXYn8L1D74HMnZhlJFldss5K0Tg5piNZ8=,tag:ndp018n5tcap1laEWCVTyQ==,type:str]
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.10.2
