# start of Meshtastic configure yaml
channel_url: https://meshtastic.org/e/#CgcSAQE6AggNEg0IATgBQARQHmgBwAYB
config:
    bluetooth:
        enabled: true
        fixedPin: 552039
        mode: FIXED_PIN
    device:
        disableTripleClick: true
        ledHeartbeatDisabled: true
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
    position:
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: base64:CN8mYHIAycBG6S3INTKZlhMpcEftaG6rLbQR1SmWk04=
        publicKey: base64:DVGf9sQb2wj5/v0AkkOB+kNgtqJyi7Y8h0bwCHKPf2g=
owner: pork koishi
owner_short: "\U0001FAA8"
