# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:wZDAzUpN7leytPPZKX+YaUGb3clfyK+dR9gh7XjL53oxs6r74pfjedNmvOjqen4Efr+2PKiO+Qg4tQ==,iv:urckeUcagudSyI7GQpIhLzghwPBdzKCtr2bNmQttw0w=,tag:iPWoIbFBYNo6PEE/Py5KIw==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:GW/BHDmr,iv:HadDpNv+XrFyfO9gxR9Q+tF2/hkm6J+SduxjivYGWCQ=,tag:1TBLutw0YfLL+UeqRhTc9A==,type:int]
        mode: FIXED_PIN
    device:
        role: CLIENT_MUTE
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 4
        ignoreMqtt: true
        region: US
        txPower: 20
    position:
        fixedPosition: true
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:aI/lZUCqI21n3q7WVgMDYRhKG1ghn913qc/Mr1e1Kn+uIGUy7KE/GHFfE7jwjsxBTByz,iv:qKjOk5CVLId1JgiVyuaPgGp7eM8feGh0Z1Mzrg1BCvo=,tag:OjZUwzOcFegaWP+umnCQeg==,type:str]
        publicKey: base64:Kz9dv/LbDcV1giPfz+QQD7NzYEa+KSCHK4u9OBJgy3o=
location:
    lat: 40.71
    lon: -73.9515
module_config: null
owner: pork donktastic
owner_short: "\U0001FACF"
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWGhCRDJrK1VXR0NDOTEw
            Ymk1MkZZdmFVQlBLRGdjcUpOd2NKaSt2eFdjCjlXZnZpaXBSQ1J2d1NucW5mU0F0
            Y29GSURzN3pXTDRZbzltQWJxbWRBZm8KLS0tIFBEdm5wZllyVm1ERDZsdFFvVmVa
            VWtDUTV2RGt5NG5qa2lkMGI3dTlCTk0KvNJdXc56LrvkaJsZpwsnUMnTCfh5xdZ0
            qIUkSg/4vQKeaOMo5sH4Tp5oqw5HmxIppHyJBzxJ513xMMX4fKADew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-25T06:08:27Z"
    mac: ENC[AES256_GCM,data:TRykj5MbGwJaf5hkoUFhX2PU3wHyjUi91AtCkixUnJJ4RqAinjNBqdDs91SxbY6E8XeDhB1IMjBWgcI9YdHNUdvrAwqNkJBfZ9GPzbNmwc3QwRc7Xd236zwqzF1dBr//dSWu33SBrMlIXPvpx+4GMyTb46XZwx3LMqDDghpYZ6A=,iv:iYTHVvyik/kLPTUkUkLe9ONtoi3LmOEbJHBbW0uFQuw=,tag:P3EoaqQte5SVOXNlNAAmHA==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
