# start of Meshtastic configure yaml
channel_url: ENC[AES256_GCM,data:Xl3lyyPPT56xuCDS9CYAO1A+WFyVoPtg+J3hOzmvsQqeresc4GOiaatfk+BssU+fHJpjHGckvFwlHQ575A==,iv:nHRtQr/9yrWaeiYhkKkJ66akpBoA3Iy2U0R59xjpga0=,tag:D5280LM53mxGo2zW9qPooA==,type:str]
config:
    bluetooth:
        enabled: true
        fixedPin: ENC[AES256_GCM,data:/YnU6FO/,iv:udOqh27KpC6XDn5lkrdlQzFh/lXm2Gv1wUo4TgTytpo=,tag:r3HYuO4iLYctvdOK+TcWpg==,type:int]
        mode: FIXED_PIN
    device:
        ledHeartbeatDisabled: true
        tzdef: EST5EDT,M3.2.0,M11.1.0
    lora:
        hopLimit: 5
        ignoreMqtt: true
        region: US
        txPower: 20
    position:
        fixedPosition: true
        gpsMode: NOT_PRESENT
    security:
        adminKey:
            - base64:DVYcURJN5/T9ANlWcINogNspTCtnW85E88QdGC8yjHg=
            - base64:M+EBhhlz15N1+tlR+x62djZzl/V2s3Q9bh+4hkvISj0=
            - base64:/EKT0S2f1y9mBEJHITqTQEr8OiKdGgCl/Ol8mtIUhzA=
        privateKey: ENC[AES256_GCM,data:OvUkvA68QGfZ30d6pJJ92CrVqxb0AU93Exe9X17Hz3+nUm+I8LZcFbNaaftl1maialrC,iv:wWVJy4kyHeC0aUklE79Sqjb2oqRGqWJva1j2QTravTE=,tag:qD/0kIsp4QKreeJtDQx+Ig==,type:str]
        publicKey: base64:Kz9dv/LbDcV1giPfz+QQD7NzYEa+KSCHK4u9OBJgy3o=
location:
    lat: 40.71
    lon: -73.9515
owner: pork donktastic
owner_short: "\U0001FACF"
# firmware: 2.5.20.4c97351 | state = 23
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1r6ys7m2gw4ukrfr7zssktvx9rrcfjjw2a79qfa7e4xy7a2lrjcrs0dnllu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwRWxJWHd1N0hOemQ3b1c0
            bFBSY0oxR0NSblZPRjdhZXdtck1wOHFWa0VFCmkzM1RpeFBTQ2QvZXRabXc0Y0xq
            aDNONy8zRTRrRzIxZDdkZHc1bFlSdmMKLS0tIGVrTlVkS3BETExpckpRYmg5dFhy
            Mk1Qc1Qzd0d6NXRMUmdoNDZIN3dqVTQKTsc6LDQrV6sPOK5/pQP60dp2MBwTm6eo
            RrGM2RzM47cekKM9K1N2vuryfjWc4/fHqE9RCzzsWNgP2pq6wy/E5w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-26T05:07:23Z"
    mac: ENC[AES256_GCM,data:dhVTJoYB9CN7EAGkUekjqZl3/jMpfGopTR6kVY0lA48JL3vLwkPtpzAn7QXXy6IBciLFEkfqr8mxvdSGbnFqNbH/JH5rLReyl+6zcm/rZAkMFdT1eA+M/7ZWT0MvH7K3SvLy2frc6OEw1ZYPJh4Ep8VI8ty6l2w9l2SpYTMNKR4=,iv:UMFa5Qwjy9j8D7PEz+bFp8JieC/x+/j/gGCGXn9gWvc=,tag:qM9GXCQhGHu6If102rFNfQ==,type:str]
    pgp: []
    encrypted_regex: channel_url|fixedPin|privateKey|password|username
    version: 3.9.3
